### PR TITLE
IMPORTANT - Fix critical errors

### PR DESCRIPTION
**Pull request by GoldenStack**
This pull request fixes some critical issues with the project. Scroll through the commits to see what I've fixed.
I've also added some general improvements that, while not critical, greatly increase the speed of the project.

### CODE REVIEW

**Comment by Alexiscomete** [comment]
This is very helpful

**Comment by GoldenStack** [comment]
Thank you! I did thousands of hours of research to improve this code, and I'm glad that people like it. I'm not completely done with the additions though, so more improvements should follow.

**Comment by JustDoom** [comment]
very nice

**Comment by NikV2** [comment]
What an amazing contribution, Thank you very much!

You have officially contributed towards a better future for society.

We shall be grateful to you.

Good work!

**Pull request merged**
